import { useMemo, useState } from "react";
import { Check, Download, Image as ImageIcon, LockKeyhole, Sparkles, Trash2, Upload, Zap } from "lucide-react";

type Item={id:string;name:string;file:File;url:string;width:number;height:number;size:number;out?:string;outSize?:number};
const bytes=(n:number)=>{const u=["B","KB","MB","GB"],i=Math.min(3,Math.floor(Math.log(Math.max(n,1))/Math.log(1024)));return `${(n/1024**i).toFixed(i?1:0)} ${u[i]}`};
const saved=(a:number,b:number)=>Math.max(0,Math.round((1-b/a)*100));

export function ImageCompressorApp(){
 const [items,setItems]=useState<Item[]>([]),[quality,setQuality]=useState(.82),[format,setFormat]=useState("image/webp"),[maxWidth,setMaxWidth]=useState(""),[maxHeight,setMaxHeight]=useState(""),[busy,setBusy]=useState(false);
 const total=useMemo(()=>items.reduce((n,x)=>n+x.size,0),[items]),out=useMemo(()=>items.reduce((n,x)=>n+(x.outSize||x.size),0),[items]);
 const add=(files:FileList|null)=>{if(!files)return;Promise.all([...files].filter(f=>f.type.startsWith("image/")).slice(0,20).map(f=>new Promise<Item>((resolve,reject)=>{const url=URL.createObjectURL(f),img=new Image();img.onload=()=>resolve({id:crypto.randomUUID(),name:f.name,file:f,url,width:img.naturalWidth,height:img.naturalHeight,size:f.size});img.onerror=reject;img.src=url;}))).then(x=>setItems(p=>[...p,...x].slice(0,20)));};
 const compress=async()=>{setBusy(true);try{const next=await Promise.all(items.map(async x=>{const img=await new Promise<HTMLImageElement>((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=x.url});let w=img.naturalWidth,h=img.naturalHeight;const scale=Math.min(1,maxWidth?+maxWidth/w:1,maxHeight?+maxHeight/h:1);w=Math.max(1,Math.round(w*scale));h=Math.max(1,Math.round(h*scale));const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d")!.drawImage(img,0,0,w,h);const b=await new Promise<Blob>((r,j)=>c.toBlob(z=>z?r(z):j(new Error("encode failed")),format,quality));return {...x,out:URL.createObjectURL(b),outSize:b.size}}));setItems(next)}finally{setBusy(false)}};
 const clear=()=>{items.forEach(x=>{URL.revokeObjectURL(x.url);if(x.out)URL.revokeObjectURL(x.out)});setItems([])};
 const download=(x:Item)=>{if(!x.out)return;const a=document.createElement("a");a.href=x.out;a.download=x.name.replace(/\.[^.]+$/i,"")+(format==="image/webp"?".webp":format==="image/png"?".png":".jpg");a.click()};
 return <div className="app"><header><a className="brand" href="#"><span><Sparkles size={17}/></span>Image<span>Compressor</span></a><div className="nav"><b><LockKeyhole size={14}/> Private by design</b><a href="https://github.com/keyars/image-compressor" target="_blank" rel="noreferrer">GitHub ↗</a></div></header>
 <main><section className="hero"><small>FREE · FAST · PRIVACY-FIRST</small><h1>Smaller images.<br/><i>Same great quality.</i></h1><p>Compress, resize and convert images instantly in your browser. No uploads, no accounts, no waiting.</p></section>
 {!items.length?<section className="drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();add(e.dataTransfer.files)}} onClick={()=>document.getElementById("files")?.click()}><input id="files" hidden type="file" accept="image/*" multiple onChange={e=>add(e.target.files)}/><div className="upload"><Upload size={28}/></div><h2>Drop images here</h2><p>or click to browse from your device</p><em>JPG · PNG · WebP · up to 20 images</em></section>:<section><div className="bar"><strong>{items.length} image{items.length>1?"s":""}</strong><span>{bytes(total)}</span><div><button onClick={()=>document.getElementById("files")?.click()}><Upload size={15}/> Add images</button><input id="files" hidden type="file" accept="image/*" multiple onChange={e=>add(e.target.files)}/><button className="clear" onClick={clear}><Trash2 size={15}/> Clear</button></div></div><div className="grid"><div className="cards">{items.map(x=><article key={x.id}><div className="thumb"><img src={x.out||x.url} alt={x.name}/><button onClick={()=>setItems(p=>p.filter(y=>y.id!==x.id))}><Trash2 size={14}/></button></div><strong title={x.name}>{x.name}</strong><small>{x.width} × {x.height} · {bytes(x.size)}</small>{x.outSize&&<div className="result"><span><Check size={13}/> {saved(x.size,x.outSize)}% smaller</span><b>{bytes(x.outSize)}</b><button onClick={()=>download(x)}><Download size={14}/></button></div>}</article>)}</div><aside><small>OPTIMIZATION</small><h2>Compression settings</h2><label>Output format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="image/webp">WebP — recommended</option><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option></select></label><label>Quality <b>{Math.round(quality*100)}%</b><input type="range" min=".2" max="1" step=".01" value={quality} onChange={e=>setQuality(+e.target.value)}/></label><div className="dims"><label>Max width<input placeholder="Original" value={maxWidth} onChange={e=>setMaxWidth(e.target.value)}/></label><label>Max height<input placeholder="Original" value={maxHeight} onChange={e=>setMaxHeight(e.target.value)}/></label></div><div className="tip"><Zap size={15}/><span>WebP is a strong default for most website images.</span></div><button className="primary" disabled={busy} onClick={compress}><Zap size={16}/>{busy?"Compressing…":"Compress images"}</button>{items.some(x=>x.outSize)&&<div className="summary"><span>Original <b>{bytes(total)}</b></span><span>Optimized <b>{bytes(out)}</b></span><span>Saved <b>{saved(total,out)}%</b></span></div>}</aside></div></section>}
 <div className="trust"><div><LockKeyhole/><b>100% private</b><span>Processing stays local.</span></div><div><Zap/><b>Instant</b><span>No server upload.</span></div><div><ImageIcon/><b>Batch ready</b><span>Optimize multiple files.</span></div></div>
 <section className="content"><small>IMAGE OPTIMIZATION MADE SIMPLE</small><h2>Compress images online without uploading them.</h2><div><p>Image Compressor is a free browser-based image optimization tool for developers, designers, marketers and everyday users. Resize images, tune quality, convert formats and download optimized files in seconds.</p><p>Your source images stay on your device while your browser performs the processing. No account or backend is required for the core workflow.</p></div></section>
 <section className="faq"><small>FAQ</small><h2>Frequently asked questions</h2><details open><summary>Are my images uploaded?</summary><p>No. Compression happens locally in your browser; the application does not need to upload source images to a server.</p></details><details><summary>Is Image Compressor free?</summary><p>Yes. It is designed as a free utility with no account required.</p></details><details><summary>Can I resize images?</summary><p>Yes. Set a maximum width, height, or both. Aspect ratio is preserved.</p></details></section></main><footer>Open-source practical web utility · Built by Keyar Srinivasan <a href="https://github.com/keyars/image-compressor">View source</a></footer></div>;
}